export const writingAssistantFolders = [
  {
    order: 1,
    key: 'lore',
    label: 'Lore',
    driveTitle: '1 Lore',
    driveFolderId: '1hAfeN6Lev2SjmF6y48PhZ3KSJXGh2Ax5',
    purpose: 'Canon, world rules, metaphysics, cultures, POIs, NPCs, creatures, events, text, and philosophy.',
  },
  {
    order: 2,
    key: 'maps',
    label: 'Maps',
    driveTitle: '2 Maps',
    driveFolderId: '1ea5cJlMyZkfvsBaq6j11Utck-mZKTFFU',
    purpose: 'Atlas references, travel continuity, map-grounded scenes, location notes, regions, and route logic.',
  },
  {
    order: 3,
    key: 'player_characters',
    label: 'Player Characters',
    driveTitle: '3 Player Characters',
    driveFolderId: '1ONYOVwyKEtgHv2oIbMaBOfzHp7mYtag9',
    purpose: 'Character voice, backstory continuity, party relationships, arcs, unresolved promises, and wounds.',
  },
  {
    order: 4,
    key: 'official_symbols',
    label: 'Official Symbols',
    driveTitle: '4 Official Symbols',
    driveFolderId: '1ZIfmuh0tBgum9Ahtg41g7-orLsYOsTND',
    purpose: 'Flags, crests, glyphs, holy marks, faction marks, visual canon, and symbolic consistency.',
  },
  {
    order: 5,
    key: 'playable_classes',
    label: 'Playable Classes',
    driveTitle: '5 Playable Classes',
    driveFolderId: '1OXex-7hI1S5_MJJWkDV37W5qDUba7Fme',
    purpose: 'Class fantasy, ability constraints, advancement language, and action consistency.',
  },
  {
    order: 6,
    key: 'playable_races',
    label: 'Playable Races',
    driveTitle: '6 Playable Races',
    driveFolderId: '1Yi7wyac0wHweqrGIy3iI-g6LYFUvtIBp',
    purpose: 'Lineage culture, biology, names, speech patterns, diaspora, and race-specific constraints.',
  },
  {
    order: 7,
    key: 'player_handbook',
    label: 'Player Handbook',
    driveTitle: 'SOTERIAN PLAYER HANDBOOK | 2026-2027',
    driveFolderId: '1h8ArVf7Z00pVQAyXhov95VjIfxr8ctbm',
    purpose: 'Published rules tone, glossary, onboarding language, and system-facing explanations.',
  },
  {
    order: 8,
    key: 'continuum_sovereign_kingdom',
    label: 'The Sovereign Kingdom',
    driveTitle: '1 The Soterian Continuum | The Sovereign Kingdom',
    driveFolderId: '1MrAeq5Nh9N2xSNyD339TWpIzO4mt17BD',
    purpose: 'Primary manuscript continuity for The Lockcaste, Veinrunner, and related drafts.',
  },
  {
    order: 9,
    key: 'continuum_short_stories',
    label: 'Short Stories',
    driveTitle: '7 The Soterian Continuum | Short Stories',
    driveFolderId: '13TYoPikq6eSGO8HFa6I-zaG2kZgtajAj',
    purpose: 'Short-form canon, tonal experiments, side stories, and peripheral continuity.',
  },
];

export const writingAssistantSubfolders = [
  '00-system',
  '01-drive-schema',
  '02-style-profiles',
  '03-prompts',
  '04-templates',
  '05-rubrics',
  '06-citation-rules',
  '07-workflows',
  '08-memory',
  '09-integrations',
  '10-exports',
];

export const writingAssistantModes = [
  'outline',
  'draft',
  'revise',
  'summarize',
  'continuity_check',
  'canon_conflict_check',
  'line_edit',
  'scene_doctor',
  'voice_match',
  'synopsis',
];

export const writingAssistantRules = [
  'Retrieve relevant canon, draft, and manuscript context before producing prose.',
  'Treat Canon as stronger than Draft, Reference, Historical, and Inspiration.',
  'Separate cited fact, plausible inference, and creative proposal.',
  'Never silently overwrite canon or manuscript truth.',
  'When sources disagree, explain the contradiction and queue a decision.',
  'Respect project scope: Global, Series, Campaign, or Private.',
  'Preserve the author voice unless the active style profile says otherwise.',
];
