insert into public.sfx_library (key, title, category, filename, path)
values
  ('ambience-pub-folk', 'Pub Folk', 'Ambience', 'AmbiencePubFolk.mp3', 'SFX/Ambience/AmbiencePubFolk.mp3'),
  ('ambience-pub-small-folk', 'Pub Small Folk', 'Ambience', 'AmbiencePubSmallFolk.mp3', 'SFX/Ambience/AmbiencePubSmallFolk.mp3'),
  ('ambience-small-town', 'Small Town', 'Ambience', 'AmbienceSmallTown.mp3', 'SFX/Ambience/AmbienceSmallTown.mp3'),
  ('ambience-small-town-cafe', 'Small Town Cafe', 'Ambience', 'AmbienceSmallTownCafe.mp3', 'SFX/Ambience/AmbienceSmallTownCafe.mp3'),
  ('ambience-stadium-roar-needtofadeout', 'Stadium Roar(needtofadeout)', 'Ambience', 'AmbienceStadiumRoar(needtofadeout).mp3', 'SFX/Ambience/AmbienceStadiumRoar(needtofadeout).mp3'),
  ('ambience-tavern-folk', 'Tavern Folk', 'Ambience', 'AmbienceTavernFolk.mp3', 'SFX/Ambience/AmbienceTavernFolk.mp3'),
  ('ambience-town-square', 'Town Square', 'Ambience', 'AmbienceTownSquare.mp3', 'SFX/Ambience/AmbienceTownSquare.mp3'),
  ('combat-attack-sword-sound', 'Attack Sword Sound', 'Combat', 'AttackSwordSound.mp3', 'SFX/Combat/AttackSwordSound.mp3'),
  ('combat-armor-impact', 'Armor Impact', 'Combat', 'CombatArmorImpact.mp3', 'SFX/Combat/CombatArmorImpact.mp3'),
  ('combat-arrow-bolt-miss', 'Arrow Bolt Miss', 'Combat', 'CombatArrowBoltMiss.mp3', 'SFX/Combat/CombatArrowBoltMiss.mp3'),
  ('combat-arrow-bolt-success', 'Arrow Bolt Success', 'Combat', 'CombatArrowBoltSuccess.mp3', 'SFX/Combat/CombatArrowBoltSuccess.mp3'),
  ('combat-axe-impact', 'Axe Impact', 'Combat', 'CombatAxeImpact.mp3', 'SFX/Combat/CombatAxeImpact.mp3'),
  ('combat-breakyard-bell', 'Breakyard Bell', 'Combat', 'CombatBreakyardBell.mp3', 'SFX/Combat/CombatBreakyardBell.mp3'),
  ('combat-coggunshot', 'Coggunshot', 'Combat', 'CombatCoggunshot.mp3', 'SFX/Combat/CombatCoggunshot.mp3'),
  ('combat-death-sound', 'Death Sound', 'Combat', 'CombatDeathSound.mp3', 'SFX/Combat/CombatDeathSound.mp3'),
  ('combat-flintlock', 'Flintlock', 'Combat', 'CombatFlintlock.mp3', 'SFX/Combat/CombatFlintlock.mp3'),
  ('combat-gunshot-echo', 'Gunshot Echo', 'Combat', 'CombatGunshotEcho.mp3', 'SFX/Combat/CombatGunshotEcho.mp3'),
  ('combat-melee', 'Melee', 'Combat', 'CombatMelee.mp3', 'SFX/Combat/CombatMelee.mp3'),
  ('combat-melee-impact', 'Melee Impact', 'Combat', 'CombatMeleeImpact.mp3', 'SFX/Combat/CombatMeleeImpact.mp3'),
  ('combat-scorpion-sting', 'Scorpion Sting', 'Combat', 'CombatScorpionSting.mp3', 'SFX/Combat/CombatScorpionSting.mp3'),
  ('combat-shield-block-success', 'Shield Block Success', 'Combat', 'CombatShieldBlockSuccess.mp3', 'SFX/Combat/CombatShieldBlockSuccess.mp3'),
  ('combat-singing-blade', 'Singing Blade', 'Combat', 'CombatSingingBlade.mp3', 'SFX/Combat/CombatSingingBlade.mp3'),
  ('combat-singing-greatsword-axe-swing', 'Singing Greatsword Axe Swing', 'Combat', 'CombatSingingGreatswordAxeSwing.mp3', 'SFX/Combat/CombatSingingGreatswordAxeSwing.mp3'),
  ('combat-slow-mo-strike', 'Slow Mo Strike', 'Combat', 'CombatSlowMoStrike.mp3', 'SFX/Combat/CombatSlowMoStrike.mp3'),
  ('combat-spear-glaive-thrust', 'Spear Glaive Thrust', 'Combat', 'CombatSpearGlaiveThrust.mp3', 'SFX/Combat/CombatSpearGlaiveThrust.mp3'),
  ('combat-stab-pierce', 'Stab Pierce', 'Combat', 'CombatStabPierce.mp3', 'SFX/Combat/CombatStabPierce.mp3'),
  ('combat-sword-fight-medium', 'Sword Fight Medium', 'Combat', 'CombatSwordFightMedium.mp3', 'SFX/Combat/CombatSwordFightMedium.mp3'),
  ('combat-sword-fight-short', 'Sword Fight Short', 'Combat', 'CombatSwordFightShort.mp3', 'SFX/Combat/CombatSwordFightShort.mp3'),
  ('combat-sword-slash', 'Sword Slash', 'Combat', 'CombatSwordSlash.mp3', 'SFX/Combat/CombatSwordSlash.mp3'),
  ('combat-weapon-impact', 'Weapon Impact', 'Combat', 'CombatWeaponImpact.mp3', 'SFX/Combat/CombatWeaponImpact.mp3'),
  ('combat-draw-sword', 'Draw Sword', 'Combat', 'DrawSword.mp3', 'SFX/Combat/DrawSword.mp3'),
  ('combat-knife-draw', 'Knife Draw', 'Combat', 'KnifeDraw.mp3', 'SFX/Combat/KnifeDraw.mp3'),
  ('combat-othrod-war-horn', 'Othrod War Horn', 'Combat', 'OthrodWarHorn.mp3', 'SFX/Combat/OthrodWarHorn.mp3'),
  ('combat-sword-clang', 'Sword Clang', 'Combat', 'SwordClang.mp3', 'SFX/Combat/SwordClang.mp3'),
  ('combat-sword-cut2', 'Sword Cut2', 'Combat', 'SwordCut2.mp3', 'SFX/Combat/SwordCut2.mp3'),
  ('combat-sword-cut-fx', 'Sword Cut FX', 'Combat', 'SwordCutFX.mp3', 'SFX/Combat/SwordCutFX.mp3'),
  ('combat-sword-parry', 'Sword Parry', 'Combat', 'SwordParry.mp3', 'SFX/Combat/SwordParry.mp3'),
  ('combat-wet-hard-impact', 'Wet Hard Impact', 'Combat', 'WetHardImpact.mp3', 'SFX/Combat/WetHardImpact.mp3'),
  ('creatures-banshee-scream', 'Banshee Scream', 'Creatures', 'BansheeScream.mp3', 'SFX/Creatures/BansheeScream.mp3'),
  ('creatures-cave-durinak-song', 'Cave Durinak Song', 'Creatures', 'CaveDurinakSong.mp3', 'SFX/Creatures/CaveDurinakSong.mp3'),
  ('creatures-crow-caw', 'Crow Caw', 'Creatures', 'CrowCaw.mp3', 'SFX/Creatures/CrowCaw.mp3'),
  ('creatures-fae-wings', 'Fae Wings', 'Creatures', 'FaeWings.mp3', 'SFX/Creatures/FaeWings.mp3'),
  ('creatures-fae-wings2', 'Fae Wings2', 'Creatures', 'FaeWings2.mp3', 'SFX/Creatures/FaeWings2.mp3'),
  ('creatures-farm-chicken', 'Farm Chicken', 'Creatures', 'FarmChicken.mp3', 'SFX/Creatures/FarmChicken.mp3'),
  ('creatures-farm-goat-bleat', 'Farm Goat Bleat', 'Creatures', 'FarmGoatBleat.mp3', 'SFX/Creatures/FarmGoatBleat.mp3'),
  ('creatures-griffon-cry', 'Griffon Cry', 'Creatures', 'GriffonCry.mp3', 'SFX/Creatures/GriffonCry.mp3'),
  ('creatures-krulmaw-growl', 'Krulmaw Growl', 'Creatures', 'KrulmawGrowl.mp3', 'SFX/Creatures/KrulmawGrowl.mp3'),
  ('creatures-phantom-cry-breeze', 'Phantom Cry Breeze', 'Creatures', 'PhantomCryBreeze.mp3', 'SFX/Creatures/PhantomCryBreeze.mp3'),
  ('creatures-satyr-horn', 'Satyr Horn', 'Creatures', 'SatyrHorn.mp3', 'SFX/Creatures/SatyrHorn.mp3'),
  ('creatures-sprite-laughing', 'Sprite Laughing', 'Creatures', 'SpriteLaughing.mp3', 'SFX/Creatures/SpriteLaughing.mp3'),
  ('creatures-werewolf-distant-howl', 'Werewolf Distant Howl', 'Creatures', 'WerewolfDistantHowl.mp3', 'SFX/Creatures/WerewolfDistantHowl.mp3'),
  ('creatures-werewolf-growl', 'Werewolf Growl', 'Creatures', 'WerewolfGrowl.mp3', 'SFX/Creatures/WerewolfGrowl.mp3'),
  ('creatures-werewolf-howl', 'Werewolf Howl', 'Creatures', 'WerewolfHowl.mp3', 'SFX/Creatures/WerewolfHowl.mp3'),
  ('creatures-werewolf-howl-cave', 'Werewolf Howl Cave', 'Creatures', 'WerewolfHowlCave.mp3', 'SFX/Creatures/WerewolfHowlCave.mp3'),
  ('dmsoundboard-joke-victory', 'Joke Victory', 'DMSoundboard', 'UIDMBoardJokeVictory.mp3', 'SFX/DMSoundboard/UIDMBoardJokeVictory.mp3'),
  ('dmsoundboard-joke-wiff', 'Joke Wiff', 'DMSoundboard', 'UIDMBoardJokeWiff.mp3', 'SFX/DMSoundboard/UIDMBoardJokeWiff.mp3'),
  ('dmsoundboard-trickster-creep', 'Trickster Creep', 'DMSoundboard', 'UIDMBoardTricksterCreep.mp3', 'SFX/DMSoundboard/UIDMBoardTricksterCreep.mp3'),
  ('dmsoundboard-balloon-burst', 'Balloon Burst', 'DMSoundboard', 'UIDMSoundBoardBalloonBurst.mp3', 'SFX/DMSoundboard/UIDMSoundBoardBalloonBurst.mp3'),
  ('dmsoundboard-crickets', 'Crickets', 'DMSoundboard', 'UIDMSoundBoardCrickets.mp3', 'SFX/DMSoundboard/UIDMSoundBoardCrickets.mp3'),
  ('dmsoundboard-joke-blunder', 'Joke Blunder', 'DMSoundboard', 'UIDMSoundBoardJokeBlunder.mp3', 'SFX/DMSoundboard/UIDMSoundBoardJokeBlunder.mp3'),
  ('dmsoundboard-joke-cartoon-slide-down', 'Joke Cartoon Slide Down', 'DMSoundboard', 'UIDMSoundBoardJokeCartoonSlideDown.mp3', 'SFX/DMSoundboard/UIDMSoundBoardJokeCartoonSlideDown.mp3'),
  ('dmsoundboard-joke-cartoon-slide-up', 'Joke Cartoon Slide Up', 'DMSoundboard', 'UIDMSoundBoardJokeCartoonSlideUp.mp3', 'SFX/DMSoundboard/UIDMSoundBoardJokeCartoonSlideUp.mp3'),
  ('dmsoundboard-joke-cartoon-spinout', 'Joke Cartoon Spinout', 'DMSoundboard', 'UIDMSoundBoardJokeCartoonSpinout.mp3', 'SFX/DMSoundboard/UIDMSoundBoardJokeCartoonSpinout.mp3'),
  ('dmsoundboard-joke-ewww-kids', 'Joke Ewww Kids', 'DMSoundboard', 'UIDMSoundBoardJokeEwwwKids.mp3', 'SFX/DMSoundboard/UIDMSoundBoardJokeEwwwKids.mp3'),
  ('dmsoundboard-joke-food-crunch', 'Joke Food Crunch', 'DMSoundboard', 'UIDMSoundBoardJokeFoodCrunch.mp3', 'SFX/DMSoundboard/UIDMSoundBoardJokeFoodCrunch.mp3'),
  ('dmsoundboard-joke-pun', 'Joke Pun', 'DMSoundboard', 'UIDMSoundBoardJokePun.mp3', 'SFX/DMSoundboard/UIDMSoundBoardJokePun.mp3'),
  ('dmsoundboard-joke-triumph', 'Joke Triumph', 'DMSoundboard', 'UIDMSoundBoardJokeTriumph.mp3', 'SFX/DMSoundboard/UIDMSoundBoardJokeTriumph.mp3'),
  ('dmsoundboard-loud-thunder', 'Loud Thunder', 'DMSoundboard', 'UIDMSoundBoardLoudThunder.mp3', 'SFX/DMSoundboard/UIDMSoundBoardLoudThunder.mp3'),
  ('dmsoundboard-men-laughing', 'Men Laughing', 'DMSoundboard', 'UIDMSoundBoardMenLaughing.mp3', 'SFX/DMSoundboard/UIDMSoundBoardMenLaughing.mp3'),
  ('dmsoundboard-nature-forest-wuid', 'Nature Forest Wuid', 'DMSoundboard', 'UIDMSoundBoardNatureForestWuid.mp3', 'SFX/DMSoundboard/UIDMSoundBoardNatureForestWuid.mp3'),
  ('dmsoundboard-nature-monster-laugh', 'Nature Monster Laugh', 'DMSoundboard', 'UIDMSoundBoardNatureMonsterLaugh.mp3', 'SFX/DMSoundboard/UIDMSoundBoardNatureMonsterLaugh.mp3'),
  ('dmsoundboard-shimmering-item', 'Shimmering Item', 'DMSoundboard', 'UIDMSoundBoardShimmeringItem.mp3', 'SFX/DMSoundboard/UIDMSoundBoardShimmeringItem.mp3'),
  ('dmsoundboard-smack', 'Smack', 'DMSoundboard', 'UIDMSoundBoardSmack.mp3', 'SFX/DMSoundboard/UIDMSoundBoardSmack.mp3'),
  ('dmsoundboard-snore', 'Snore', 'DMSoundboard', 'UIDMSoundBoardSnore.mp3', 'SFX/DMSoundboard/UIDMSoundBoardSnore.mp3'),
  ('dmsoundboard-splat', 'Splat', 'DMSoundboard', 'UIDMSoundBoardSplat.mp3', 'SFX/DMSoundboard/UIDMSoundBoardSplat.mp3'),
  ('dmsoundboard-thunder-long', 'Thunder Long', 'DMSoundboard', 'UIDMSoundBoardThunderLong.mp3', 'SFX/DMSoundboard/UIDMSoundBoardThunderLong.mp3'),
  ('dmsoundboard-toddler-laughing-long', 'Toddler Laughing Long', 'DMSoundboard', 'UIDMSoundBoardToddlerLaughingLong.mp3', 'SFX/DMSoundboard/UIDMSoundBoardToddlerLaughingLong.mp3'),
  ('dmsoundboard-trickster-laugh', 'Trickster Laugh', 'DMSoundboard', 'UIDMSoundBoardTricksterLaugh.mp3', 'SFX/DMSoundboard/UIDMSoundBoardTricksterLaugh.mp3'),
  ('dmsoundboard-water-splash', 'Water Splash', 'DMSoundboard', 'UIDMSoundBoardWaterSplash.mp3', 'SFX/DMSoundboard/UIDMSoundBoardWaterSplash.mp3'),
  ('dmsoundboard-whistle-catcall', 'Whistle Catcall', 'DMSoundboard', 'UIDMSoundBoardWhistleCatcall.mp3', 'SFX/DMSoundboard/UIDMSoundBoardWhistleCatcall.mp3'),
  ('dmsoundboard-whistle-heyoo', 'Whistle HEYOO', 'DMSoundboard', 'UIDMSoundBoardWhistleHEYOO.mp3', 'SFX/DMSoundboard/UIDMSoundBoardWhistleHEYOO.mp3'),
  ('dmsoundboard-whistle-signal', 'Whistle Signal', 'DMSoundboard', 'UIDMSoundBoardWhistleSignal.mp3', 'SFX/DMSoundboard/UIDMSoundBoardWhistleSignal.mp3'),
  ('dmsoundboard-whistle-theme', 'Whistle Theme', 'DMSoundboard', 'UIDMSoundBoardWhistleTheme.mp3', 'SFX/DMSoundboard/UIDMSoundBoardWhistleTheme.mp3'),
  ('environment-cave-boom', 'Cave Boom', 'Environment', 'CaveBoom.mp3', 'SFX/Environment/CaveBoom.mp3'),
  ('environment-dungeon-echo', 'Dungeon Echo', 'Environment', 'DungeonEcho.mp3', 'SFX/Environment/DungeonEcho.mp3'),
  ('environment-underwater', 'Underwater', 'Environment', 'Environment-Underwater.mp3', 'SFX/Environment/Environment-Underwater.mp3'),
  ('environment-bird-chirp', 'Bird Chirp', 'Environment', 'EnvironmentBirdChirp.mp3', 'SFX/Environment/EnvironmentBirdChirp.mp3'),
  ('environment-camp-w-fire', 'Camp W Fire', 'Environment', 'EnvironmentCampWFire.mp3', 'SFX/Environment/EnvironmentCampWFire.mp3'),
  ('environment-campfire-woods', 'Campfire Woods', 'Environment', 'EnvironmentCampfireWoods.mp3', 'SFX/Environment/EnvironmentCampfireWoods.mp3'),
  ('environment-cave', 'Cave', 'Environment', 'EnvironmentCave.mp3', 'SFX/Environment/EnvironmentCave.mp3'),
  ('environment-coast', 'Coast', 'Environment', 'EnvironmentCoast.mp3', 'SFX/Environment/EnvironmentCoast.mp3'),
  ('environment-coastline', 'Coastline', 'Environment', 'EnvironmentCoastline.mp3', 'SFX/Environment/EnvironmentCoastline.mp3'),
  ('environment-creek-peaceful', 'Creek Peaceful', 'Environment', 'EnvironmentCreekPeaceful.mp3', 'SFX/Environment/EnvironmentCreekPeaceful.mp3'),
  ('environment-forest', 'Forest', 'Environment', 'EnvironmentForest.mp3', 'SFX/Environment/EnvironmentForest.mp3'),
  ('environment-forest-walking', 'Forest Walking', 'Environment', 'EnvironmentForestWalking.mp3', 'SFX/Environment/EnvironmentForestWalking.mp3'),
  ('environment-forest-waterfall', 'Forest Waterfall', 'Environment', 'EnvironmentForestWaterfall.mp3', 'SFX/Environment/EnvironmentForestWaterfall.mp3'),
  ('environment-high-winds', 'High Winds', 'Environment', 'EnvironmentHighWinds.mp3', 'SFX/Environment/EnvironmentHighWinds.mp3'),
  ('environment-mountain-river', 'Mountain River', 'Environment', 'EnvironmentMountainRiver.mp3', 'SFX/Environment/EnvironmentMountainRiver.mp3'),
  ('environment-nature', 'Nature', 'Environment', 'EnvironmentNature.mp3', 'SFX/Environment/EnvironmentNature.mp3'),
  ('environment-nighttime', 'Nighttime', 'Environment', 'EnvironmentNighttime.mp3', 'SFX/Environment/EnvironmentNighttime.mp3'),
  ('environment-old-mine', 'Old Mine', 'Environment', 'EnvironmentOldMine.mp3', 'SFX/Environment/EnvironmentOldMine.mp3'),
  ('environment-plains', 'Plains', 'Environment', 'EnvironmentPlains.mp3', 'SFX/Environment/EnvironmentPlains.mp3'),
  ('environment-rain', 'Rain', 'Environment', 'EnvironmentRain.mp3', 'SFX/Environment/EnvironmentRain.mp3'),
  ('environment-rain-city', 'Rain City', 'Environment', 'EnvironmentRainCity.mp3', 'SFX/Environment/EnvironmentRainCity.mp3'),
  ('environment-summer-day', 'Summer Day', 'Environment', 'EnvironmentSummerDay.mp3', 'SFX/Environment/EnvironmentSummerDay.mp3'),
  ('environment-thunderstorm', 'Thunderstorm', 'Environment', 'EnvironmentThunderstorm.mp3', 'SFX/Environment/EnvironmentThunderstorm.mp3'),
  ('environment-windy-mountain-pass', 'Windy Mountain Pass', 'Environment', 'EnvironmentWindyMountainPass.mp3', 'SFX/Environment/EnvironmentWindyMountainPass.mp3'),
  ('environment-footsteps-loud', 'Footsteps Loud', 'Environment', 'Footsteps-Loud.mp3', 'SFX/Environment/Footsteps-Loud.mp3'),
  ('horror-ambience', 'Ambience', 'Horror', 'HorrorAmbience.mp3', 'SFX/Horror/HorrorAmbience.mp3'),
  ('horror-dropoff-sound', 'Dropoff Sound', 'Horror', 'HorrorDropoffSound.mp3', 'SFX/Horror/HorrorDropoffSound.mp3'),
  ('horror-steampunk-scratch-through-wall', 'Steampunk Scratch Through Wall', 'Horror', 'HorrorSteampunkScratchThroughWall.mp3', 'SFX/Horror/HorrorSteampunkScratchThroughWall.mp3'),
  ('horror-suspense-sound', 'Suspense Sound', 'Horror', 'HorrorSuspenseSound.mp3', 'SFX/Horror/HorrorSuspenseSound.mp3'),
  ('horror-trombone-crescendo', 'Trombone Crescendo', 'Horror', 'HorrorTromboneCrescendo.mp3', 'SFX/Horror/HorrorTromboneCrescendo.mp3'),
  ('horror-wraith-scream', 'Wraith Scream', 'Horror', 'HorrorWraithScream.mp3', 'SFX/Horror/HorrorWraithScream.mp3'),
  ('horror-the-voicesinthe-void', 'The Voicesinthe Void', 'Horror', 'TheVoicesintheVoid.mp3', 'SFX/Horror/TheVoicesintheVoid.mp3'),
  ('magic-alchemist-beaker', 'Alchemist Beaker', 'Magic', 'AlchemistBeaker.mp3', 'SFX/Magic/AlchemistBeaker.mp3'),
  ('magic-blessing-boon', 'Blessing Boon', 'Magic', 'Blessing-Boon.mp3', 'SFX/Magic/Blessing-Boon.mp3'),
  ('magic-fast-mote', 'Fast Mote', 'Magic', 'FastMote.mp3', 'SFX/Magic/FastMote.mp3'),
  ('magic-healing-spell', 'Healing Spell', 'Magic', 'HealingSpell.mp3', 'SFX/Magic/HealingSpell.mp3'),
  ('magic-illusion-spell', 'Illusion Spell', 'Magic', 'IllusionSpell.mp3', 'SFX/Magic/IllusionSpell.mp3'),
  ('magic-lightning-spell', 'Lightning Spell', 'Magic', 'LightningSpell.mp3', 'SFX/Magic/LightningSpell.mp3'),
  ('magic-lightning-spellgreater', 'Lightning Spellgreater', 'Magic', 'LightningSpellgreater.mp3', 'SFX/Magic/LightningSpellgreater.mp3'),
  ('magic-blast', 'Blast', 'Magic', 'MagicBlast.mp3', 'SFX/Magic/MagicBlast.mp3'),
  ('magic-charm', 'Charm', 'Magic', 'MagicCharm.mp3', 'SFX/Magic/MagicCharm.mp3'),
  ('magic-chime', 'Chime', 'Magic', 'MagicChime.mp3', 'SFX/Magic/MagicChime.mp3'),
  ('magic-chime2', 'Chime2', 'Magic', 'MagicChime2.mp3', 'SFX/Magic/MagicChime2.mp3'),
  ('magic-discovery', 'Discovery', 'Magic', 'MagicDiscovery.mp3', 'SFX/Magic/MagicDiscovery.mp3'),
  ('magic-druid', 'Druid', 'Magic', 'MagicDruid.mp3', 'SFX/Magic/MagicDruid.mp3'),
  ('magic-element-cast', 'Element Cast', 'Magic', 'MagicElementCast.mp3', 'SFX/Magic/MagicElementCast.mp3'),
  ('magic-element-cast2', 'Element Cast2', 'Magic', 'MagicElementCast2.mp3', 'SFX/Magic/MagicElementCast2.mp3'),
  ('magic-fae-chime', 'Fae Chime', 'Magic', 'MagicFaeChime.mp3', 'SFX/Magic/MagicFaeChime.mp3'),
  ('magic-fire-extinguish', 'Fire Extinguish', 'Magic', 'MagicFireExtinguish.mp3', 'SFX/Magic/MagicFireExtinguish.mp3'),
  ('magic-fire-impact', 'Fire Impact', 'Magic', 'MagicFireImpact.mp3', 'SFX/Magic/MagicFireImpact.mp3'),
  ('magic-fire-impact-huge', 'Fire Impact Huge', 'Magic', 'MagicFireImpactHuge.mp3', 'SFX/Magic/MagicFireImpactHuge.mp3'),
  ('magic-fire-impact-large', 'Fire Impact Large', 'Magic', 'MagicFireImpactLarge.mp3', 'SFX/Magic/MagicFireImpactLarge.mp3'),
  ('magic-fireball', 'Fireball', 'Magic', 'MagicFireball.mp3', 'SFX/Magic/MagicFireball.mp3'),
  ('magic-fireball2', 'Fireball2', 'Magic', 'MagicFireball2.mp3', 'SFX/Magic/MagicFireball2.mp3'),
  ('magic-glyph-lock', 'Glyph Lock', 'Magic', 'MagicGlyphLock.mp3', 'SFX/Magic/MagicGlyphLock.mp3'),
  ('magic-heal-cast', 'Heal Cast', 'Magic', 'MagicHealCast.mp3', 'SFX/Magic/MagicHealCast.mp3'),
  ('magic-illusion', 'Illusion', 'Magic', 'MagicIllusion.mp3', 'SFX/Magic/MagicIllusion.mp3'),
  ('magic-impact', 'Impact', 'Magic', 'MagicImpact.mp3', 'SFX/Magic/MagicImpact.mp3'),
  ('magic-impact-large', 'Impact Large', 'Magic', 'MagicImpactLarge.mp3', 'SFX/Magic/MagicImpactLarge.mp3'),
  ('magic-loot-equip', 'Loot Equip', 'Magic', 'MagicLootEquip.mp3', 'SFX/Magic/MagicLootEquip.mp3'),
  ('magic-mote', 'Mote', 'Magic', 'MagicMote.mp3', 'SFX/Magic/MagicMote.mp3'),
  ('magic-rock-spell', 'Rock Spell', 'Magic', 'MagicRockSpell.mp3', 'SFX/Magic/MagicRockSpell.mp3'),
  ('magic-rock-spell2', 'Rock Spell2', 'Magic', 'MagicRockSpell2.mp3', 'SFX/Magic/MagicRockSpell2.mp3'),
  ('magic-sacral', 'Sacral', 'Magic', 'MagicSacral.mp3', 'SFX/Magic/MagicSacral.mp3'),
  ('magic-sanctus', 'Sanctus', 'Magic', 'MagicSanctus.mp3', 'SFX/Magic/MagicSanctus.mp3'),
  ('magic-sanctus-heal', 'Sanctus Heal', 'Magic', 'MagicSanctusHeal.mp3', 'SFX/Magic/MagicSanctusHeal.mp3'),
  ('magic-shaeid', 'Shaeid', 'Magic', 'MagicShaeid.mp3', 'SFX/Magic/MagicShaeid.mp3'),
  ('magic-shimmer', 'Shimmer', 'Magic', 'MagicShimmer.mp3', 'SFX/Magic/MagicShimmer.mp3'),
  ('magic-silly-hover-spell', 'Silly Hover Spell', 'Magic', 'MagicSillyHoverSpell.mp3', 'SFX/Magic/MagicSillyHoverSpell.mp3'),
  ('magic-sparkle-whoosh', 'Sparkle Whoosh', 'Magic', 'MagicSparkleWhoosh.mp3', 'SFX/Magic/MagicSparkleWhoosh.mp3'),
  ('magic-strike', 'Strike', 'Magic', 'MagicStrike.mp3', 'SFX/Magic/MagicStrike.mp3'),
  ('magic-success', 'Success', 'Magic', 'MagicSuccess.mp3', 'SFX/Magic/MagicSuccess.mp3'),
  ('magic-summon', 'Summon', 'Magic', 'MagicSummon.mp3', 'SFX/Magic/MagicSummon.mp3'),
  ('magic-teleport', 'Teleport', 'Magic', 'MagicTeleport.mp3', 'SFX/Magic/MagicTeleport.mp3'),
  ('magic-twinkle', 'Twinkle', 'Magic', 'MagicTwinkle.mp3', 'SFX/Magic/MagicTwinkle.mp3'),
  ('magic-water-cast', 'Water Cast', 'Magic', 'MagicWaterCast.mp3', 'SFX/Magic/MagicWaterCast.mp3'),
  ('magic-whoosh2', 'Whoosh2', 'Magic', 'MagicWhoosh2.mp3', 'SFX/Magic/MagicWhoosh2.mp3'),
  ('magic-wind', 'Wind', 'Magic', 'MagicWind.mp3', 'SFX/Magic/MagicWind.mp3'),
  ('magic-wind-cast', 'Wind Cast', 'Magic', 'MagicWindCast.mp3', 'SFX/Magic/MagicWindCast.mp3'),
  ('magic-wish', 'Wish', 'Magic', 'MagicWish.mp3', 'SFX/Magic/MagicWish.mp3'),
  ('magic-wish-cast', 'Wish Cast', 'Magic', 'MagicWishCast.mp3', 'SFX/Magic/MagicWishCast.mp3'),
  ('magic-wraill', 'Wraill', 'Magic', 'MagicWraill.mp3', 'SFX/Magic/MagicWraill.mp3'),
  ('magic-wraill-cast', 'Wraill Cast', 'Magic', 'MagicWraillCast.mp3', 'SFX/Magic/MagicWraillCast.mp3'),
  ('magic-mystical-chime', 'Mystical Chime', 'Magic', 'MysticalChime.mp3', 'SFX/Magic/MysticalChime.mp3'),
  ('misc-hercules', 'Hercules', 'Misc', 'Hercules.mp3', 'SFX/Misc/Hercules.mp3'),
  ('steampunk-healing-tech', 'Healing Tech', 'Steampunk', 'HealingTech.mp3', 'SFX/Steampunk/HealingTech.mp3'),
  ('steampunk-schematic-charging', 'Schematic Charging', 'Steampunk', 'SchematicCharging.mp3', 'SFX/Steampunk/SchematicCharging.mp3'),
  ('steampunk-schematic-whirring-ding', 'Schematic Whirring Ding', 'Steampunk', 'SchematicWhirringDing.mp3', 'SFX/Steampunk/SchematicWhirringDing.mp3'),
  ('steampunk-schematic-whistle', 'Schematic Whistle', 'Steampunk', 'SchematicWhistle.mp3', 'SFX/Steampunk/SchematicWhistle.mp3'),
  ('steampunk-sci-fi-blast', 'Sci Fi Blast', 'Steampunk', 'SciFiBlast.mp3', 'SFX/Steampunk/SciFiBlast.mp3'),
  ('steampunk-automaton-footprints', 'Automaton Footprints', 'Steampunk', 'SteampunkAutomatonFootprints.mp3', 'SFX/Steampunk/SteampunkAutomatonFootprints.mp3'),
  ('steampunk-automaton-power-down', 'Automaton Power Down', 'Steampunk', 'SteampunkAutomatonPowerDown.mp3', 'SFX/Steampunk/SteampunkAutomatonPowerDown.mp3'),
  ('steampunk-automaton-weapon', 'Automaton Weapon', 'Steampunk', 'SteampunkAutomatonWeapon.mp3', 'SFX/Steampunk/SteampunkAutomatonWeapon.mp3'),
  ('steampunk-blueprint-deploy-chime', 'Blueprint Deploy Chime', 'Steampunk', 'SteampunkBlueprintDeployChime.mp3', 'SFX/Steampunk/SteampunkBlueprintDeployChime.mp3'),
  ('steampunk-blueprint-loading', 'Blueprint Loading', 'Steampunk', 'SteampunkBlueprintLoading.mp3', 'SFX/Steampunk/SteampunkBlueprintLoading.mp3'),
  ('steampunk-cannon-gun', 'Cannon Gun', 'Steampunk', 'SteampunkCannonGun.mp3', 'SFX/Steampunk/SteampunkCannonGun.mp3'),
  ('steampunk-catapult-small', 'Catapult Small', 'Steampunk', 'SteampunkCatapultSmall.mp3', 'SFX/Steampunk/SteampunkCatapultSmall.mp3'),
  ('steampunk-charge-ready', 'Charge Ready', 'Steampunk', 'SteampunkChargeReady.mp3', 'SFX/Steampunk/SteampunkChargeReady.mp3'),
  ('steampunk-chronison-calibrating', 'Chronison Calibrating', 'Steampunk', 'SteampunkChronisonCalibrating.mp3', 'SFX/Steampunk/SteampunkChronisonCalibrating.mp3'),
  ('steampunk-chronison-corrupted', 'Chronison Corrupted', 'Steampunk', 'SteampunkChronisonCorrupted.mp3', 'SFX/Steampunk/SteampunkChronisonCorrupted.mp3'),
  ('steampunk-confused-robot', 'Confused Robot', 'Steampunk', 'SteampunkConfusedRobot.mp3', 'SFX/Steampunk/SteampunkConfusedRobot.mp3'),
  ('steampunk-deploy-success', 'Deploy Success', 'Steampunk', 'SteampunkDeploySuccess.mp3', 'SFX/Steampunk/SteampunkDeploySuccess.mp3'),
  ('steampunk-deployment-damaged', 'Deployment Damaged', 'Steampunk', 'SteampunkDeploymentDamaged.mp3', 'SFX/Steampunk/SteampunkDeploymentDamaged.mp3'),
  ('steampunk-engine-running-low', 'Engine Running Low', 'Steampunk', 'SteampunkEngineRunningLow.mp3', 'SFX/Steampunk/SteampunkEngineRunningLow.mp3'),
  ('steampunk-friendly-robot', 'Friendly Robot', 'Steampunk', 'SteampunkFriendlyRobot.mp3', 'SFX/Steampunk/SteampunkFriendlyRobot.mp3'),
  ('steampunk-gadget-close', 'Gadget Close', 'Steampunk', 'SteampunkGadgetClose.mp3', 'SFX/Steampunk/SteampunkGadgetClose.mp3'),
  ('steampunk-gear-startup-short', 'Gear Startup Short', 'Steampunk', 'SteampunkGearStartupShort.mp3', 'SFX/Steampunk/SteampunkGearStartupShort.mp3'),
  ('steampunk-hack-attempt-fail', 'Hack Attempt Fail', 'Steampunk', 'SteampunkHackAttemptFail.mp3', 'SFX/Steampunk/SteampunkHackAttemptFail.mp3'),
  ('steampunk-hydraulic', 'Hydraulic', 'Steampunk', 'SteampunkHydraulic.mp3', 'SFX/Steampunk/SteampunkHydraulic.mp3'),
  ('steampunk-machine-blip', 'Machine Blip', 'Steampunk', 'SteampunkMachineBlip.mp3', 'SFX/Steampunk/SteampunkMachineBlip.mp3'),
  ('steampunk-machine-hack', 'Machine Hack', 'Steampunk', 'SteampunkMachineHack.mp3', 'SFX/Steampunk/SteampunkMachineHack.mp3'),
  ('steampunk-machine-sound', 'Machine Sound', 'Steampunk', 'SteampunkMachineSound.mp3', 'SFX/Steampunk/SteampunkMachineSound.mp3'),
  ('steampunk-machine-tuning', 'Machine Tuning', 'Steampunk', 'SteampunkMachineTuning.mp3', 'SFX/Steampunk/SteampunkMachineTuning.mp3'),
  ('steampunk-mechanical-gears-loud', 'Mechanical Gears LOUD', 'Steampunk', 'SteampunkMechanicalGearsLOUD.mp3', 'SFX/Steampunk/SteampunkMechanicalGearsLOUD.mp3'),
  ('steampunk-phaser-fire', 'Phaser Fire', 'Steampunk', 'SteampunkPhaserFire.mp3', 'SFX/Steampunk/SteampunkPhaserFire.mp3'),
  ('steampunk-plasma-impact', 'Plasma Impact', 'Steampunk', 'SteampunkPlasmaImpact.mp3', 'SFX/Steampunk/SteampunkPlasmaImpact.mp3'),
  ('steampunk-plasma-shot', 'Plasma Shot', 'Steampunk', 'SteampunkPlasmaShot.mp3', 'SFX/Steampunk/SteampunkPlasmaShot.mp3'),
  ('steampunk-recall-deployment', 'Recall Deployment', 'Steampunk', 'SteampunkRecallDeployment.mp3', 'SFX/Steampunk/SteampunkRecallDeployment.mp3'),
  ('steampunk-robot-power-down', 'Robot Power Down', 'Steampunk', 'SteampunkRobotPowerDown.mp3', 'SFX/Steampunk/SteampunkRobotPowerDown.mp3'),
  ('steampunk-robot-power-on', 'Robot Power On', 'Steampunk', 'SteampunkRobotPowerOn.mp3', 'SFX/Steampunk/SteampunkRobotPowerOn.mp3'),
  ('steampunk-schematic-deploy', 'Schematic Deploy', 'Steampunk', 'SteampunkSchematicDeploy.mp3', 'SFX/Steampunk/SteampunkSchematicDeploy.mp3'),
  ('steampunk-sending-correspondence', 'Sending Correspondence', 'Steampunk', 'SteampunkSendingCorrespondence.mp3', 'SFX/Steampunk/SteampunkSendingCorrespondence.mp3'),
  ('steampunk-small-gear-wind', 'Small Gear Wind', 'Steampunk', 'SteampunkSmallGearWind.mp3', 'SFX/Steampunk/SteampunkSmallGearWind.mp3'),
  ('steampunk-tinkertrick-deploy-large', 'Tinkertrick Deploy Large', 'Steampunk', 'SteampunkTinkertrickDeployLarge.mp3', 'SFX/Steampunk/SteampunkTinkertrickDeployLarge.mp3'),
  ('steampunk-tinkertrick-deploy-long', 'Tinkertrick Deploy Long', 'Steampunk', 'SteampunkTinkertrickDeployLong.mp3', 'SFX/Steampunk/SteampunkTinkertrickDeployLong.mp3'),
  ('steampunk-tinkertrick-deploy-small', 'Tinkertrick Deploy Small', 'Steampunk', 'SteampunkTinkertrickDeploySmall.mp3', 'SFX/Steampunk/SteampunkTinkertrickDeploySmall.mp3'),
  ('steampunk-upgrade-chime', 'Upgrade Chime', 'Steampunk', 'SteampunkUpgradeChime.mp3', 'SFX/Steampunk/SteampunkUpgradeChime.mp3'),
  ('steampunk-warpshot', 'Warpshot', 'Steampunk', 'SteampunkWarpshot.mp3', 'SFX/Steampunk/SteampunkWarpshot.mp3'),
  ('steampunk-weapon-equip', 'Weapon Equip', 'Steampunk', 'SteampunkWeaponEquip.mp3', 'SFX/Steampunk/SteampunkWeaponEquip.mp3'),
  ('steampunk-white-noise-fail-5-min', 'White Noise Fail 5 Min', 'Steampunk', 'SteampunkWhiteNoiseFail-5Min.mp3', 'SFX/Steampunk/SteampunkWhiteNoiseFail-5Min.mp3'),
  ('steampunk-windup-deploy', 'Windup Deploy', 'Steampunk', 'SteampunkWindupDeploy.mp3', 'SFX/Steampunk/SteampunkWindupDeploy.mp3'),
  ('ui-cinema-whoosh', 'Cinema Whoosh', 'UI', 'CinemaWhoosh.mp3', 'SFX/UI/CinemaWhoosh.mp3'),
  ('ui-coin-drop', 'Coin Drop', 'UI', 'CoinDrop.mp3', 'SFX/UI/CoinDrop.mp3'),
  ('ui-game-start-lobby-checkin', 'Game Start Lobby Checkin', 'UI', 'GameStartLobbyCheckin.mp3', 'SFX/UI/GameStartLobbyCheckin.mp3'),
  ('ui-level-up-chime', 'Level Up Chime', 'UI', 'LevelUpChime.mp3', 'SFX/UI/LevelUpChime.mp3'),
  ('ui-notification1', 'Notification1', 'UI', 'Notification1.mp3', 'SFX/UI/Notification1.mp3'),
  ('ui-skill-up', 'Skill Up', 'UI', 'SkillUp.mp3', 'SFX/UI/SkillUp.mp3'),
  ('ui-swipe-confirm', 'Swipe Confirm', 'UI', 'SwipeConfirm.mp3', 'SFX/UI/SwipeConfirm.mp3'),
  ('ui-ap-grant-chime', 'AP Grant Chime', 'UI', 'UIAPGrantChime.mp3', 'SFX/UI/UIAPGrantChime.mp3'),
  ('ui-audio-file-playback-end', 'Audio File Playback End', 'UI', 'UIAudioFilePlaybackEnd.mp3', 'SFX/UI/UIAudioFilePlaybackEnd.mp3'),
  ('ui-audio-file-playback-start', 'Audio File Playback Start', 'UI', 'UIAudioFilePlaybackStart.mp3', 'SFX/UI/UIAudioFilePlaybackStart.mp3'),
  ('ui-blip', 'Blip', 'UI', 'UIBlip.mp3', 'SFX/UI/UIBlip.mp3'),
  ('ui-blip2', 'Blip2', 'UI', 'UIBlip2.mp3', 'SFX/UI/UIBlip2.mp3'),
  ('ui-blip3', 'Blip3', 'UI', 'UIBlip3.mp3', 'SFX/UI/UIBlip3.mp3'),
  ('ui-blip4', 'Blip4', 'UI', 'UIBlip4.mp3', 'SFX/UI/UIBlip4.mp3'),
  ('ui-campaign-dm-view-page-pop', 'Campaign DM View Page Pop', 'UI', 'UICampaignDMViewPagePop.mp3', 'SFX/UI/UICampaignDMViewPagePop.mp3'),
  ('ui-chime-high', 'Chime High', 'UI', 'UIChimeHigh.mp3', 'SFX/UI/UIChimeHigh.mp3'),
  ('ui-chime-low', 'Chime Low', 'UI', 'UIChimeLow.mp3', 'SFX/UI/UIChimeLow.mp3'),
  ('ui-click', 'Click', 'UI', 'UIClick.mp3', 'SFX/UI/UIClick.mp3'),
  ('ui-close-sound', 'Close Sound', 'UI', 'UICloseSound.mp3', 'SFX/UI/UICloseSound.mp3'),
  ('ui-coin-payout-big', 'Coin Payout Big', 'UI', 'UICoinPayoutBig.mp3', 'SFX/UI/UICoinPayoutBig.mp3'),
  ('ui-confirm-chime', 'Confirm Chime', 'UI', 'UIConfirmChime.mp3', 'SFX/UI/UIConfirmChime.mp3'),
  ('ui-dm-sent-ding', 'DM Sent Ding', 'UI', 'UIDMSentDing.mp3', 'SFX/UI/UIDMSentDing.mp3'),
  ('ui-delete', 'Delete', 'UI', 'UIDelete.mp3', 'SFX/UI/UIDelete.mp3'),
  ('ui-dice-crit-fail', 'Dice Crit Fail', 'UI', 'UIDiceCritFail.mp3', 'SFX/UI/UIDiceCritFail.mp3'),
  ('ui-dice-crit-success', 'Dice Crit Success', 'UI', 'UIDiceCritSuccess.mp3', 'SFX/UI/UIDiceCritSuccess.mp3'),
  ('ui-grimoire-entry-unlock', 'Grimoire Entry Unlock', 'UI', 'UIGrimoireEntryUnlock.mp3', 'SFX/UI/UIGrimoireEntryUnlock.mp3'),
  ('ui-loot-box-open', 'Loot Box Open', 'UI', 'UILootBoxOpen.mp3', 'SFX/UI/UILootBoxOpen.mp3'),
  ('ui-menu-commit', 'Menu Commit', 'UI', 'UIMenuCommit.mp3', 'SFX/UI/UIMenuCommit.mp3'),
  ('ui-message', 'Message', 'UI', 'UIMessage.mp3', 'SFX/UI/UIMessage.mp3'),
  ('ui-navigate-deny', 'Navigate Deny', 'UI', 'UINavigateDeny.mp3', 'SFX/UI/UINavigateDeny.mp3'),
  ('ui-new-quest', 'New Quest', 'UI', 'UINewQuest.mp3', 'SFX/UI/UINewQuest.mp3'),
  ('ui-notify', 'Notify', 'UI', 'UINotify.mp3', 'SFX/UI/UINotify.mp3'),
  ('ui-on-click', 'On Click', 'UI', 'UIOnClick.mp3', 'SFX/UI/UIOnClick.mp3'),
  ('ui-quest-accept', 'Quest Accept', 'UI', 'UIQuestAccept.mp3', 'SFX/UI/UIQuestAccept.mp3'),
  ('ui-quest-complete', 'Quest Complete', 'UI', 'UIQuestComplete.mp3', 'SFX/UI/UIQuestComplete.mp3'),
  ('ui-quest-step-complete', 'Quest Step Complete', 'UI', 'UIQuestStepComplete.mp3', 'SFX/UI/UIQuestStepComplete.mp3'),
  ('ui-reveal', 'Reveal', 'UI', 'UIReveal.mp3', 'SFX/UI/UIReveal.mp3'),
  ('ui-scribe-token-grant', 'Scribe Token Grant', 'UI', 'UIScribeTokenGrant.mp3', 'SFX/UI/UIScribeTokenGrant.mp3'),
  ('ui-scribe-token-spend', 'Scribe Token Spend', 'UI', 'UIScribeTokenSpend.mp3', 'SFX/UI/UIScribeTokenSpend.mp3'),
  ('ui-select-confirm', 'Select Confirm', 'UI', 'UISelectConfirm.mp3', 'SFX/UI/UISelectConfirm.mp3'),
  ('ui-spell-mote-chime', 'Spell Mote Chime', 'UI', 'UISpellMoteChime.mp3', 'SFX/UI/UISpellMoteChime.mp3'),
  ('ui-strange-whoosh', 'Strange Whoosh', 'UI', 'UIStrangeWhoosh.mp3', 'SFX/UI/UIStrangeWhoosh.mp3'),
  ('ui-tutorial', 'Tutorial', 'UI', 'UITutorial.mp3', 'SFX/UI/UITutorial.mp3'),
  ('ui-unlock', 'Unlock', 'UI', 'UIUnlock.mp3', 'SFX/UI/UIUnlock.mp3'),
  ('ui-warn', 'Warn', 'UI', 'UIWarn.mp3', 'SFX/UI/UIWarn.mp3')
on conflict (key) do update set
  title = excluded.title,
  category = excluded.category,
  filename = excluded.filename,
  path = excluded.path;
