// AUTO-GENERATED by scripts/generate-maps-manifest.cjs — do not edit by hand.
// Regenerated on build, on dev start, and whenever public/Maps changes.
// This is only "what is on disk"; hand-written display names live in the
// curated list in MapPanel.jsx, which takes precedence over anything here.
export const GENERATED_MAPS = [
  {
    "id": "albion",
    "name": "Albion",
    "filename": "Albion.png"
  },
  {
    "id": "aridara",
    "name": "Aridara",
    "filename": "Aridara.png"
  },
  {
    "id": "ashendell",
    "name": "Ashendell",
    "filename": "Ashendell.png"
  },
  {
    "id": "avalora",
    "name": "Avalora",
    "filename": "Avalora.png"
  },
  {
    "id": "avalora-colliseum1",
    "name": "Avalora Colliseum1",
    "filename": "AvaloraColliseum1.png"
  },
  {
    "id": "avalora-colliseum2",
    "name": "Avalora Colliseum2",
    "filename": "AvaloraColliseum2.png"
  },
  {
    "id": "avalora-colliseum3",
    "name": "Avalora Colliseum3",
    "filename": "AvaloraColliseum3.png"
  },
  {
    "id": "brivihan-plains",
    "name": "Brivihan Plains",
    "filename": "Brivihan Plains.png"
  },
  {
    "id": "broken-cathedral",
    "name": "Broken Cathedral",
    "filename": "BrokenCathedral.png"
  },
  {
    "id": "chronolithe-wastes",
    "name": "Chronolithe Wastes",
    "filename": "Chronolithe Wastes.png"
  },
  {
    "id": "chronolithe-wastes2",
    "name": "Chronolithe Wastes2",
    "filename": "ChronolitheWastes2.png"
  },
  {
    "id": "cielo-dorado",
    "name": "Cielo Dorado",
    "filename": "CieloDorado.png"
  },
  {
    "id": "dorhaven-penthosanctum",
    "name": "Dorhaven Penthosanctum",
    "filename": "Dorhaven-Penthosanctum.png"
  },
  {
    "id": "dungeon-cathedral-sword",
    "name": "Dungeon Cathedral Sword",
    "filename": "DungeonCathedralSword.png"
  },
  {
    "id": "dungeon-chronolithe-wastes",
    "name": "Dungeon Chronolithe Wastes",
    "filename": "DungeonChronolitheWastes.png"
  },
  {
    "id": "dungeon-maze",
    "name": "Dungeon Maze",
    "filename": "DungeonMaze.png"
  },
  {
    "id": "dungeon-puzzle",
    "name": "Dungeon Puzzle",
    "filename": "DungeonPuzzle.png"
  },
  {
    "id": "dungeon-puzzle2",
    "name": "Dungeon Puzzle2",
    "filename": "DungeonPuzzle2.png"
  },
  {
    "id": "ebba",
    "name": "Ebba",
    "filename": "Ebba.png"
  },
  {
    "id": "elddim",
    "name": "elddim",
    "filename": "elddim.png"
  },
  {
    "id": "elmoire-2",
    "name": "Elmoire 2",
    "filename": "Elmoire 2.png"
  },
  {
    "id": "epham",
    "name": "Epham",
    "filename": "Epham.png"
  },
  {
    "id": "galekgarde",
    "name": "galekgarde",
    "filename": "galekgarde.png"
  },
  {
    "id": "gamdon",
    "name": "gamdon",
    "filename": "gamdon.png"
  },
  {
    "id": "gamdonbeyondportal",
    "name": "Gamdonbeyondportal",
    "filename": "Gamdonbeyondportal.png"
  },
  {
    "id": "golgothapass",
    "name": "golgothapass",
    "filename": "golgothapass.png"
  },
  {
    "id": "hadmont",
    "name": "Hadmont",
    "filename": "Hadmont.png"
  },
  {
    "id": "karak-byrn",
    "name": "Karak Byrn",
    "filename": "Karak Byrn.png"
  },
  {
    "id": "lilith-iel-south",
    "name": "Lilith'iel South",
    "filename": "Lilith'iel South.png"
  },
  {
    "id": "lilith-iel-cirusons-resting-place",
    "name": "Lilith'iel Cirusons Resting Place",
    "filename": "Lilith'ielCirusonsRestingPlace.png"
  },
  {
    "id": "lutetia-testudon-pirate-cove",
    "name": "Lutetia Testudon Pirate Cove",
    "filename": "Lutetia-TestudonPirateCove.png"
  },
  {
    "id": "maakurg-s-altar1",
    "name": "Maakurg's Altar1",
    "filename": "Maakurg'sAltar1.png"
  },
  {
    "id": "maakurg-s-altar2",
    "name": "Maakurg's Altar2",
    "filename": "Maakurg'sAltar2.png"
  },
  {
    "id": "maakurg-s-altar3",
    "name": "Maakurg's Altar3",
    "filename": "Maakurg'sAltar3.png"
  },
  {
    "id": "maakurg-s-altar4",
    "name": "Maakurg's Altar4",
    "filename": "Maakurg'sAltar4.png"
  },
  {
    "id": "makeda-kwetu",
    "name": "Makeda Kwetu",
    "filename": "MakedaKwetu.png"
  },
  {
    "id": "marigizh-ar",
    "name": "Marigizh'ar",
    "filename": "Marigizh'ar.png"
  },
  {
    "id": "mouthofthe-wastes",
    "name": "Mouthofthe Wastes",
    "filename": "MouthoftheWastes.png"
  },
  {
    "id": "mouthofthe-wastes2",
    "name": "Mouthofthe Wastes2",
    "filename": "MouthoftheWastes2.png"
  },
  {
    "id": "murinorburrowhold",
    "name": "Murinorburrowhold",
    "filename": "Murinorburrowhold.png"
  },
  {
    "id": "n-quythalas-2",
    "name": "N'quythalas 2",
    "filename": "N'quythalas 2.png"
  },
  {
    "id": "n-quythalas",
    "name": "N'quythalas",
    "filename": "N'quythalas.png"
  },
  {
    "id": "n-quythalasdepths",
    "name": "N'quythalasdepths",
    "filename": "N'quythalasdepths.png"
  },
  {
    "id": "ormr",
    "name": "Ormr",
    "filename": "Ormr.png"
  },
  {
    "id": "quynthe-ra",
    "name": "quynthe'ra",
    "filename": "quynthe'ra.png"
  },
  {
    "id": "ra-kesh",
    "name": "Ra'Kesh",
    "filename": "Ra'Kesh.png"
  },
  {
    "id": "razor-s-point",
    "name": "Razor's Point",
    "filename": "Razor'sPoint.png"
  },
  {
    "id": "rimehollow-knoll-camp",
    "name": "Rimehollow Knoll Camp",
    "filename": "Rimehollow-KnollCamp.png"
  },
  {
    "id": "rimehollow-knoll-dungeon",
    "name": "Rimehollow Knoll Dungeon",
    "filename": "Rimehollow-KnollDungeon.png"
  },
  {
    "id": "rimehollow-edge",
    "name": "Rimehollow Edge",
    "filename": "RimehollowEdge.png"
  },
  {
    "id": "rookvale-warman-s-lake",
    "name": "Rookvale,Warman's Lake",
    "filename": "Rookvale,Warman'sLake.png"
  },
  {
    "id": "soteria-world-map",
    "name": "Soteria World Map",
    "filename": "SoteriaWorldMap.jpg"
  },
  {
    "id": "sovereign-gale",
    "name": "Sovereign Gale",
    "filename": "Sovereign Gale.png"
  },
  {
    "id": "tarek-mor",
    "name": "Tarek'Mor",
    "filename": "Tarek'Mor.png"
  },
  {
    "id": "thereienstadt",
    "name": "Thereienstadt",
    "filename": "Thereienstadt.png"
  },
  {
    "id": "the-veiled-knolls",
    "name": "the Veiled Knolls",
    "filename": "theVeiledKnolls.png"
  },
  {
    "id": "trystique",
    "name": "Trystique",
    "filename": "Trystique.png"
  },
  {
    "id": "valorhold",
    "name": "Valorhold",
    "filename": "Valorhold.png"
  },
  {
    "id": "verdeli-ere",
    "name": "Verdeli'ere",
    "filename": "Verdeli'ere.png"
  },
  {
    "id": "village",
    "name": "Village",
    "filename": "Village.png"
  },
  {
    "id": "vlareth",
    "name": "Vlareth",
    "filename": "Vlareth.png"
  },
  {
    "id": "vonyal",
    "name": "Vonyal",
    "filename": "Vonyal.png"
  },
  {
    "id": "vonyal-entrance",
    "name": "Vonyal Entrance",
    "filename": "VonyalEntrance.png"
  },
  {
    "id": "woodpath",
    "name": "woodpath",
    "filename": "woodpath.png"
  },
  {
    "id": "zephyria",
    "name": "Zephyria",
    "filename": "Zephyria.png"
  },
  {
    "id": "zephyria-collegebehindtheveil",
    "name": "Zephyria Collegebehindtheveil",
    "filename": "ZephyriaCollegebehindtheveil.png"
  },
  {
    "id": "zeppelin",
    "name": "Zeppelin",
    "filename": "Zeppelin.png"
  }
];
